### ISSUE TITLE
PyGeometry first draft

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-geometry#12]
Let's get a first version of the Geometry client out!

Related tasks:
- [x] Create a base repository + docs repos for getting things started
- [x] Implement basic entity objects. Linked to #13 
- [x] Implement units handling using ``pint``. Linked to #2 
- [x] Create a plotting module for visualizing the entity objects. Linked to #3 
- [x] Create a math/algebra module for operations with entity objects. Linked to #13
- [x] Conceive a simple client to connect to a gRPC server. Linked to #36 
- [x] Add tests
- [x] Add documentation: API reference automatically generated + basic PyAnsys sections. Linked to #5 
- [x] Add examples. Linked to #4
