### ISSUE TITLE
Classes to prototype

### ISSUE THREAD

**Issue by akaszynski** [ansys/pyansys-geometry#13]
### Basic Math Capabilities
- [x] Point #16 
- [x] Vector3D #18 
- [x] VectorUV #18 
- [x] Direction (Unit Vector) #16 
- [x] Matrix #40 

### 2D Geometry
- [x] Line #54
- [x] Segment #54 
- [x] Circle #19 
- [x] 2DSpline #46 (NOT A PRIORITY)
- [x] Ellipse #19 
- [x] Polygon #52  
- [x] Arc #50  

### 3D Geometry
- [x] Plane #32
- [x] Sphere #24
- [x] Cylinder #23
- [x] Torus #20 
- [x] Cone #30
- [x] 3DSpline #46 (NOT A PRIORITY)
- [x] Line Segment #33 
 
### Misc
- [x] BBox #21 (NOT A PRIORITY)
- [x] Interval #22 (NOT A PRIORITY)
- [x] Frame #51 
- [x] Accuracy (operation tolerance (e.g. `Point3D == Point3D` or `Point3d.is_equal(<other point, tol=1E-5)` #35

### Units
- [x] ~Metric~
- [x] ~Imperial~
- [x] [pint](https://github.com/hgrecco/pint)

Additional requirements
- [x] Null state (e.g. initialized with `Point3D()`)
