### ISSUE TITLE
TODO tracklist for longterm items

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-geometry#1319]
Instead of creating individual issues I will track the longterm TODOs here:

- [ ] Increase server stats when reporting - see connection/validate.py
- [ ] Remove support for old server versions not having "tool_bodies" - see designer/body.py
- [ ] Allow passing a list of materials instead of one by one - see designer/design.py
- [ ] Adding Design ID to material request - see  designer/design.py
- [ ] Ensure design sync is complete - see designer/design.py
- [ ] Increase support for material properties - see designer/design.py
- [ ] SharedTopology sync is time consuming  - see designer/design.py
- [ ] Inform via logger that if a Quantity is given to a Measurement object, its unit value is disregarded - misc/measurements.py
- [ ] Repair tools available on Linux - see modeler.py
- [ ] Include support for perimeter and area on TrimmedSurfaces - see shapes/srufaces/trimmed_surface.py
- [ ] On Box sketch creation we should be able to pass in the plane for creating the SketchSegment - see sketch/box.py
- [ ] There are certain sketches like Circle and Ellipse that are a SketchFace and are not making use of the edges - see sketch/face.py

**Comment by RobPasMue** [comment]
@pyansys-automation never close issue
